# Generated by Django 6.0.6 on 2026-06-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='plan',
            field=models.TextField(default='Old Trip'),
            preserve_default=False,
        ),
    ]
