# Generated by Django 6.0.6 on 2026-06-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='activities_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='emergency_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='food_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='shopping_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='transport_budget',
            field=models.IntegerField(default=0),
        ),
    ]
