# Generated by Django 6.0.6 on 2026-07-15 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_activities_budget_trip_emergency_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
